-- INSERT statements for meterstatistics.csv to billingdata.meters table
-- Generated with property_id assignment:
--   Company 3 (Glostrup Boligselskab): property_id randomly from {1, 2}
--   Company 59 (Carlsberg Breweries A/S): property_id randomly from {3, 4}
--   Company 67 (KAB s m b a): property_id randomly from {5, 6}
-- Missing fields (active_management_read, active_garbage_meter_read) set to 0
-- Timestamp set to 2026-01-19 00:00:00

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  1,
  'Glostrup Boligselskab',
  'GB afd. 16 Diget 78',
  3,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  2,
  'Glostrup Boligselskab',
  'Brøndbyvestervej/Gyvelvej',
  9,
  7,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  4,
  'Glostrup Boligselskab',
  'GB afd. 30 Granskoven/Egeskoven Fælles',
  12,
  9,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  5,
  'Glostrup Boligselskab',
  'GB afd. 32 Lindeskoven',
  3,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  7,
  'Glostrup Boligselskab',
  'GB afd. 08 Hovedvejen /Bryggergårdsvej 2A',
  12,
  8,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  9,
  'Glostrup Boligselskab',
  'GB afd. 18 Ærtebjergvej',
  7,
  0,
  7,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  11,
  'Glostrup Boligselskab',
  'Toftevej 6-10',
  5,
  3,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  12,
  'Glostrup Boligselskab',
  'GB afd. 25 Asylvej',
  5,
  3,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  13,
  'Glostrup Boligselskab',
  'GB afd. 28 Lilliendalsvej',
  6,
  3,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  14,
  'Glostrup Boligselskab',
  'GB afd. 29 Stenager Fælles',
  13,
  11,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  15,
  'Glostrup Boligselskab',
  'Gadager 9 Materialegård',
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  16,
  'Glostrup Boligselskab',
  'GB afd. 33 Birke-/Bøgeskoven',
  20,
  17,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  19,
  'Glostrup Boligselskab',
  'GB afd. 37 Egeskoven',
  5,
  3,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  20,
  'Glostrup Boligselskab',
  'GB afd. 49 Stenager 6',
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  21,
  'Glostrup Boligselskab',
  'GB afd. 50 Bryggergårdsvej 1A og 1B (Ungbo)',
  5,
  3,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  22,
  'Glostrup Boligselskab',
  'GB afd. 59 Stenager',
  4,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  23,
  'Glostrup Boligselskab',
  'G/F Egeskoven',
  3,
  0,
  0,
  0,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  34,
  'Glostrup Boligselskab',
  'Afd. 01 A Ndr. Ringvej 16-22',
  9,
  5,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  35,
  'Glostrup Boligselskab',
  'Afd. 01 B Ndr. Ringvej 24-28',
  10,
  5,
  5,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  36,
  'Glostrup Boligselskab',
  'Afd. 01 C Ndr. Ringvej 30-34 og Vestervej 43',
  8,
  4,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  37,
  'Glostrup Boligselskab',
  'Afd. 01 D Vestervej 33-37',
  5,
  3,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  38,
  'Glostrup Boligselskab',
  'Afd. 01 E Vestervej 27-31',
  5,
  3,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  40,
  'Glostrup Boligselskab',
  'Sportsvej 15A - Garage',
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  41,
  'Glostrup Boligselskab',
  'Leddet 2-4',
  2,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  43,
  'Glostrup Boligselskab',
  'Diget 80',
  4,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  44,
  'Glostrup Boligselskab',
  'Diget 02-16',
  20,
  3,
  17,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  45,
  'Glostrup Boligselskab',
  'Diget 1-27',
  16,
  4,
  12,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  46,
  'Glostrup Boligselskab',
  'Sportsvej 33 – 39',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  47,
  'Glostrup Boligselskab',
  'Sportsvej 53-59',
  8,
  2,
  6,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  48,
  'Glostrup Boligselskab',
  'Sportsvej 75 – 81',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  49,
  'Glostrup Boligselskab',
  'Sportsvej 60',
  4,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  50,
  'Glostrup Boligselskab',
  'Sportsvej 20 - 22',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  51,
  'Glostrup Boligselskab',
  'Stubben 2-18',
  13,
  6,
  7,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  3536,
  'Glostrup Boligselskab',
  'GB afd. 38 - Sydvestvej 32 & 34',
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8315,
  'Glostrup Boligselskab',
  'Skellet 1-11',
  9,
  5,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8316,
  'Glostrup Boligselskab',
  'Brinken 1-17',
  12,
  5,
  7,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8317,
  'Glostrup Boligselskab',
  'Hegnet 1-11',
  6,
  2,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8318,
  'Glostrup Boligselskab',
  'Gærdet 1-7',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8319,
  'Glostrup Boligselskab',
  'Sportsvej 07',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8320,
  'Glostrup Boligselskab',
  'Sportsvej 09',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8321,
  'Glostrup Boligselskab',
  'Sportsvej 11',
  6,
  2,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8322,
  'Glostrup Boligselskab',
  'Sportsvej 13',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8323,
  'Glostrup Boligselskab',
  'Sportsvej 15',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8324,
  'Glostrup Boligselskab',
  'Rødkælkevej 090',
  8,
  5,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8325,
  'Glostrup Boligselskab',
  'Rødkælkevej 162',
  8,
  5,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8326,
  'Glostrup Boligselskab',
  'Rødkælkevej 164',
  8,
  5,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8327,
  'Glostrup Boligselskab',
  'Rødkælkevej 240',
  8,
  5,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8328,
  'Glostrup Boligselskab',
  'Rødkælkevej 242',
  8,
  5,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8329,
  'Glostrup Boligselskab',
  'Rødkælkevej 326',
  8,
  5,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8330,
  'Glostrup Boligselskab',
  'Rødkælkevej 328',
  8,
  5,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8331,
  'Glostrup Boligselskab',
  'Rødkælkevej 414',
  8,
  5,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8332,
  'Glostrup Boligselskab',
  'Rødkælkevej 088',
  8,
  5,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8333,
  'Glostrup Boligselskab',
  'Rødkælkevej 030',
  8,
  5,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8334,
  'Glostrup Boligselskab',
  'Rødkælkevej  198',
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8335,
  'Glostrup Boligselskab',
  'Rødkælkevej  122',
  2,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8337,
  'Glostrup Boligselskab',
  'Diget 29-31',
  7,
  2,
  5,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8340,
  'Glostrup Boligselskab',
  'Sportsvej 62',
  4,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8342,
  'Glostrup Boligselskab',
  'Brøndbyvestervej 21 – 29',
  6,
  5,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8344,
  'Glostrup Boligselskab',
  'Diget 33-35',
  6,
  2,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8345,
  'Glostrup Boligselskab',
  'Diget 37-39',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8346,
  'Glostrup Boligselskab',
  'Diget 41-43',
  6,
  2,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8347,
  'Glostrup Boligselskab',
  'Diget 45-47',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8348,
  'Glostrup Boligselskab',
  'Diget 82-86',
  3,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8349,
  'Glostrup Boligselskab',
  'Diget 88-92',
  4,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8350,
  'Glostrup Boligselskab',
  'Diget 94-98',
  4,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8351,
  'Glostrup Boligselskab',
  'Diget 100-104',
  6,
  4,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8355,
  'Glostrup Boligselskab',
  'Leddet 1-3',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8356,
  'Glostrup Boligselskab',
  'Leddet 5-7',
  7,
  2,
  5,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8357,
  'Glostrup Boligselskab',
  'Leddet 9-11',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8358,
  'Glostrup Boligselskab',
  'Leddet 13-15',
  7,
  2,
  5,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8360,
  'Glostrup Boligselskab',
  'Leddet 18-20',
  4,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8361,
  'Glostrup Boligselskab',
  'Leddet 14-16',
  3,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8362,
  'Glostrup Boligselskab',
  'Leddet 10-12',
  3,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8363,
  'Glostrup Boligselskab',
  'Leddet 6-8',
  3,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8367,
  'Glostrup Boligselskab',
  'Hegnet 1-27',
  9,
  3,
  6,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8368,
  'Glostrup Boligselskab',
  'Sportsvej 41-51',
  7,
  2,
  5,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8377,
  'Glostrup Boligselskab',
  'Sportsvej 17-23',
  4,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8378,
  'Glostrup Boligselskab',
  'Sportsvej 25 – 31',
  5,
  2,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8379,
  'Glostrup Boligselskab',
  'Sportsvej 61 – 67',
  6,
  2,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8380,
  'Glostrup Boligselskab',
  'Sportsvej 69 – 73',
  7,
  2,
  5,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  8381,
  'Glostrup Boligselskab',
  'Sportsvej 83',
  4,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  8386,
  'Glostrup Boligselskab',
  'Vestervej 19-25',
  4,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  19252,
  'Glostrup Boligselskab',
  'Stenager 193 vaskeri',
  5,
  3,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  19253,
  'Glostrup Boligselskab',
  'Stenager 209 Etageboliger',
  6,
  4,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  1,
  19255,
  'Glostrup Boligselskab',
  'Granskoven 171 vaskeri og beboerlokale',
  5,
  3,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  19256,
  'Glostrup Boligselskab',
  'Granskoven 173 Hvissingenet',
  7,
  3,
  0,
  1,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  19258,
  'Glostrup Boligselskab',
  'Gadager 76 Varmecentral',
  7,
  5,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  19259,
  'Glostrup Boligselskab',
  'Gadager 96 Vaskeri',
  9,
  4,
  4,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  3,
  2,
  19261,
  'Glostrup Boligselskab',
  'Østre Lindeskov 209 vaskeri',
  5,
  4,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  3,
  2648,
  'Carlsberg Breweries A/S',
  'Carlsberg Museum',
  6,
  5,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  3,
  2649,
  'Carlsberg Breweries A/S',
  'Carls Villa',
  3,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  4,
  2650,
  'Carlsberg Breweries A/S',
  'Gl.C og Bryggeri',
  86,
  78,
  0,
  6,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  3,
  2651,
  'Carlsberg Breweries A/S',
  'CRL Carlsberg Forskningscenter',
  20,
  12,
  3,
  5,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  3,
  2652,
  'Carlsberg Breweries A/S',
  'Carlsberg Bryghus',
  4,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  3,
  2707,
  'Carlsberg Breweries A/S',
  'Silo-Malteri',
  3,
  0,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  3,
  2798,
  'Carlsberg Breweries A/S',
  'Gl.C.V. 8',
  5,
  4,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  3,
  3018,
  'Carlsberg Breweries A/S',
  'Akademiet',
  2,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  4,
  8394,
  'Carlsberg Breweries A/S',
  'CCO',
  11,
  9,
  0,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  3,
  32014,
  'Carlsberg Breweries A/S',
  'Enablon Bryggeri',
  3,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  4,
  33838,
  'Carlsberg Breweries A/S',
  'Fiktiv bygning til rapportering - mike ',
  2,
  0,
  0,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  4,
  34805,
  'Carlsberg Breweries A/S',
  'Fiktiv bygning Madklubben ',
  2,
  0,
  0,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  59,
  4,
  34808,
  'Carlsberg Breweries A/S',
  'Traitomic svalehuset',
  4,
  0,
  0,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  6,
  2690,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1001-6 Frederiksholm, Karré 1',
  35,
  11,
  21,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  3
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  5,
  2691,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1002-3 Frederiksholm, Karré 2',
  32,
  3,
  28,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  5,
  2692,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1003-0 Frederiksholm, Karré 3',
  51,
  1,
  23,
  0,
  0,
  27,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  6,
  2693,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1004-8 Frederiksholm, Karré 4',
  16,
  1,
  12,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  6,
  2694,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1005-5 Frederiksholm, Karré 5',
  14,
  2,
  12,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  5,
  2695,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1006-2 Frederiksholm, Karré 6',
  26,
  1,
  25,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  6,
  2696,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1007-0 Frederiksholm, Karré 7',
  18,
  1,
  17,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  6,
  2697,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1008-7 Frederiksholm, Karré 8',
  17,
  0,
  16,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  5,
  2698,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1009-4 Grønnegården',
  44,
  2,
  41,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  6,
  2699,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1010-4 Frederiksholm, Karré 11',
  8,
  1,
  7,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  5,
  2700,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1011-1 Frederiksholm, Karré 12',
  15,
  6,
  9,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  6,
  2701,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1012-9 Frederiksholm, Karré 14',
  11,
  1,
  10,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  5,
  2702,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1013-6 Frederiksholm, Karré 15',
  41,
  2,
  36,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  5,
  2703,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1014-3 Frederiksholm, Børnegården',
  7,
  1,
  6,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  6,
  2704,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1029-5 Frederiksholm, Karré 17',
  19,
  1,
  18,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  5,
  2705,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1046-4 Frederiksholm, Karré 18',
  16,
  1,
  15,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  5,
  2706,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1052-0 Engholmen Nord',
  6,
  1,
  5,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

INSERT INTO billingdata.meters (
  timestamp,
  company_id,
  property_id,
  building_id,
  company_name,
  building_name,
  total,
  actively_remote_read,
  active_manual_read,
  active_calculation_meters,
  inactive_remotely_read,
  inactive_manually_read,
  inactive_calculation_meters,
  unsupported_remotely_read,
  unsupported_manually_read,
  unsupported_calculation_meters,
  active_management_read,
  active_garbage_meter_read
) VALUES (
  timestamp '2026-01-19 00:00:00',
  67,
  6,
  2722,
  'KAB s m b a (Boligselskabet AKB-København)',
  '1047 Frederiksholm',
  3,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
);

